# Generated by Django 4.0.4 on 2022-07-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form1_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_mob_no', models.CharField(max_length=200)),
                ('patient_desiese_symptom', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=200)),
                ('curr_date_time', models.DateTimeField()),
                ('time', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='form2_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_mob_no', models.CharField(max_length=200)),
                ('patient_desiese_symptom', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=200)),
                ('curr_date_time', models.DateTimeField()),
                ('time', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='form3_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_mob_no', models.CharField(max_length=200)),
                ('patient_desiese_symptom', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=200)),
                ('curr_date_time', models.DateTimeField()),
                ('time', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='form4_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_mob_no', models.CharField(max_length=200)),
                ('patient_desiese_symptom', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=200)),
                ('curr_date_time', models.DateTimeField()),
                ('time', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='form5_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_mob_no', models.CharField(max_length=200)),
                ('patient_desiese_symptom', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=200)),
                ('curr_date_time', models.DateTimeField()),
                ('time', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='form6_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_mob_no', models.CharField(max_length=200)),
                ('patient_desiese_symptom', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=200)),
                ('curr_date_time', models.DateTimeField()),
                ('time', models.CharField(max_length=200)),
            ],
        ),
    ]
