# Generated by Django 4.0.4 on 2022-07-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1_data',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='form1_data',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='form2_data',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='form2_data',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='form3_data',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='form3_data',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='form4_data',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='form4_data',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='form5_data',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='form5_data',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='form6_data',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='form6_data',
            name='time',
            field=models.TimeField(),
        ),
    ]
