# Generated by Django 4.0.4 on 2022-07-06 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A1', '0003_contact_us'),
    ]

    operations = [
        migrations.DeleteModel(
            name='form1_data',
        ),
    ]
