# Generated by Django 4.0.4 on 2022-07-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A1', '0004_delete_form1_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='form1_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_mob_no', models.CharField(max_length=200)),
                ('patient_desiese_symptom', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('curr_date_time', models.DateTimeField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
